 "use client";
import Link from "next/link";
import { ArrowRight, CheckCircle2, Loader2 } from "lucide-react";
import { FormEvent, useState } from "react";
import { AuthCard, AuthInput, AuthShell } from "../auth-components";
import { createClient } from "../../lib/supabase/client";

export default function SignupPage() {
 const supabase=createClient(); const [loading,setLoading]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget);const fullName=String(f.get("fullName")||"").trim(),email=String(f.get("email")||"").trim().toLowerCase(),password=String(f.get("password")||""),confirm=String(f.get("confirmPassword")||"");if(!fullName||!email||!password)return setError("Please complete all required fields.");if(password.length<8)return setError("Password must be at least 8 characters.");if(password!==confirm)return setError("Passwords do not match.");setLoading(true);const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name:fullName},emailRedirectTo:`${window.location.origin}/onboarding`}});setLoading(false);if(error)return setError(error.message);sessionStorage.setItem("campusmind_pending_email",email);setSuccess(true);}
 if(success)return <AuthShell><AuthCard eyebrow="Account created" title="Check your email." description="Your CampusMind account has been created. Verify your email before continuing."><div className="auth-success"><CheckCircle2 size={28}/><strong>Verification email sent</strong><span>We sent a verification message to your email address.</span></div><Link href="/verify-email" className="auth-button">Continue to verification <ArrowRight size={17}/></Link></AuthCard></AuthShell>;
 return <AuthShell><AuthCard eyebrow="Create your account" title="Welcome to CampusMind." description="Create your free account and start building a smarter academic workflow."><form className="auth-form" onSubmit={submit}><AuthInput label="Full name" name="fullName" placeholder="Enter your full name"/><AuthInput label="Email address" name="email" type="email" placeholder="you@example.com"/><AuthInput label="Password" name="password" type="password" placeholder="Create a password"/><AuthInput label="Confirm password" name="confirmPassword" type="password" placeholder="Confirm your password"/><label className="auth-check"><input type="checkbox" required/><span>I agree to the <Link href="#">Terms of Service</Link> and <Link href="#">Privacy Policy</Link>.</span></label>{error&&<div className="auth-error">{error}</div>}<button className="auth-button" disabled={loading}>{loading?<><Loader2 className="spin" size={17}/> Creating account...</>:<>Create Account <ArrowRight size={17}/></>}</button></form><div className="auth-divider"><span>Already have an account?</span></div><Link href="/login" className="auth-outline">Log in</Link><div className="auth-note"><CheckCircle2 size={15}/> Free to get started. No payment required.</div></AuthCard></AuthShell>;
}
