 "use client";
import Link from "next/link";
import { ArrowRight,Loader2,LockKeyhole } from "lucide-react";
import { FormEvent,useState } from "react";
import { AuthCard,AuthShell } from "../auth-components";
import { createClient } from "../../lib/supabase/client";

export default function LoginPage(){const supabase=createClient();const [loading,setLoading]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget),email=String(f.get("email")||"").trim().toLowerCase(),password=String(f.get("password")||"");if(!email||!password)return setError("Enter your email and password.");setLoading(true);const {error}=await supabase.auth.signInWithPassword({email,password});setLoading(false);if(error)return setError(error.message);window.location.href="/dashboard";}
 return <AuthShell><AuthCard eyebrow="Welcome back" title="Log in to CampusMind." description="Pick up where you left off and keep your academic work moving."><form className="auth-form" onSubmit={submit}><label className="auth-label">Email address<input name="email" type="email" placeholder="you@example.com"/></label><div><div className="auth-label-row"><span>Password</span><Link href="/forgot-password">Forgot password?</Link></div><input name="password" className="auth-input" type="password" placeholder="Enter your password"/></div>{error&&<div className="auth-error">{error}</div>}<label className="auth-check"><input type="checkbox"/><span>Remember me</span></label><button className="auth-button" disabled={loading}>{loading?<><Loader2 className="spin" size={17}/> Logging in...</>:<>Log In <ArrowRight size={17}/></>}</button></form><div className="auth-divider"><span>Don&apos;t have an account?</span></div><Link href="/signup" className="auth-outline">Create a free account</Link><div className="auth-note"><LockKeyhole size={15}/> Your account is protected by secure authentication.</div></AuthCard></AuthShell>}
